name: Test Action

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Test
        run: cargo test --locked

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build Action image
        run: docker build --tag daily-standup-meetings:test .
