name: Test Action

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 24.20.0

      - name: Install
        run: yarn install --immutable

      - name: Checks
        run: yarn checks run --no-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: yarn library build

      - name: Verify committed build
        run: git diff --exit-code -- dist
